app:
  name: "web_app"
  port: 8080

logger:
  level: "debug"
  filename: "logs/web_app.logs"
  max_size: 200
  max_age: 30
  max_backups: 7
  isCompress: true

mysql:
  host: "localhost"
  port: ***
  username: "root"
  password: "123456"
  dbname: "db1"
  SetMaxOpenConns: 200
  SetMaxIdleConns: 50

redis:
  host: "127.0.0.1"
  port: ***
  password: ""
  db: 0
  poolsize: 100